### ISSUE TITLE
Add OTP tests

### ISSUE THREAD

**Issue by robin-nitrokey** [Nitrokey/nitrokey-3-tests#16]
> - for a simple test, you could start by copying and adapting TestFido2: https://github.com/Nitrokey/nitrokey-3-tests/blob/main/tests/basic.py
> - for more complicated tests, you could add a tests/otp.py file and add several tests

**Comment by szszszsz** [comment]
Just for the future: I wonder, if using `pexpect` directly is the right way to do it. Click has its own testing support:
- https://click.palletsprojects.com/en/8.1.x/testing/

**Comment by robin-nitrokey** [comment]
Interesting!  I’m not really happy with the output that `pexpect` produces on errors so I’m open to alternatives.
